create table if not exists public.climate_reports (
  report_key text primary key,
  generated_at timestamptz not null,
  report jsonb not null,
  is_public boolean not null default false,
  alert_count integer not null default 0,
  news_count integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.climate_reports
add column if not exists is_public boolean not null default false;

alter table public.climate_reports enable row level security;

drop policy if exists "public can read latest climate reports" on public.climate_reports;
create policy "public can read latest climate reports"
on public.climate_reports
for select
to anon, authenticated
using (is_public = true);

drop policy if exists "service role can write climate reports" on public.climate_reports;
create policy "service role can write climate reports"
on public.climate_reports
for all
to service_role
using (true)
with check (true);

create index if not exists climate_reports_generated_at_idx
on public.climate_reports (generated_at desc);

create table if not exists public.notification_subscriptions (
  endpoint text primary key,
  device_id text not null,
  subscription jsonb not null,
  lat double precision not null,
  lng double precision not null,
  min_level text not null default 'ama',
  user_agent text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now()),
  revoked_at timestamptz
);

update public.notification_subscriptions
set
  lat = round(lat::numeric, 2)::double precision,
  lng = round(lng::numeric, 2)::double precision
where lat <> round(lat::numeric, 2)::double precision
   or lng <> round(lng::numeric, 2)::double precision;

alter table public.notification_subscriptions enable row level security;

drop policy if exists "service role can manage notification subscriptions" on public.notification_subscriptions;
create policy "service role can manage notification subscriptions"
on public.notification_subscriptions
for all
to service_role
using (true)
with check (true);

create index if not exists notification_subscriptions_active_idx
on public.notification_subscriptions (revoked_at, updated_at desc);

create index if not exists notification_subscriptions_device_idx
on public.notification_subscriptions (device_id);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  device_id text not null,
  endpoint text,
  alert_id text not null,
  alert_level text not null default 'ama',
  reason text not null default 'region-match',
  payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz not null default timezone('utc', now())
);

alter table public.notification_deliveries enable row level security;

drop policy if exists "service role can manage notification deliveries" on public.notification_deliveries;
create policy "service role can manage notification deliveries"
on public.notification_deliveries
for all
to service_role
using (true)
with check (true);

create unique index if not exists notification_deliveries_unique_delivery_idx
on public.notification_deliveries (device_id, alert_id, reason);

create index if not exists notification_deliveries_alert_idx
on public.notification_deliveries (alert_id, sent_at desc);
